/**
 * Util file for all the color's used
 * 
 */
export default {
    BLACK: "#000000",
    WHITE: "#FFFFFF",
    TRANSPARENT: "#FFFFFF00",
    RED: "#FF0000",
    GREY: "#FAFAFA",
    QUIZ_GREY: "#f6f6f6",
    DARK_BACKGROUND: '#201734',
    TOOLBAR_BACKGROUND: '#2017344D',
    BUTTON_BACKGROUND: '#FC3FA8',
    THUMB_COLOR_DISABLED: "#7E788B",
    TOGGLE_BACKGROUND_TRACK: "#767577",
    BLACK_TRASNPARENT: '#201734B3',
    GREY_TRANSPARENT: '#BDB9C2B3',
    WHITE_TRANSPARENT: '#ffffff3D',
    WHITE_QUIZ_TRANSPARENT: '#ffffffCC',
    THUMB_APP_BLUE: '#4317AF',
    THUMB_BACKGROUND: '#C4D0DC',
    APP_BLUE: '#4317AF',
    APP_DARK_BLUE: '#201734',
    APP_DARK_BLUE_TRANSPARENT: '#2017343D',
    EMOTICONS_BACKGROUND: '#FFFFFF3D',
    EMOTICONS_BACKGROUND_SELECTED: '#FFFFFFAA',
    POLL_TEXT_COLOR: '#363240',
    QUIZ_BORDER_GREY: '#D7D5DB',
    QUIZ_WRONG_ANS_BACKGROUND: '#DED4F7'
}